package com.repopilot.patch.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.http.HttpClient;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.repopilot.common.ApiException;
import com.sun.net.httpserver.HttpServer;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

class ConfiguredCoderModelClientTest {

    private final ObjectMapper objectMapper = new ObjectMapper();
    private HttpServer server;

    @AfterEach
    void tearDown() {
        if (server != null) {
            server.stop(0);
        }
    }

    @Test
    void generatePatchReturnsEmptyWhenDisabled() {
        ConfiguredCoderModelClient client = new ConfiguredCoderModelClient("disabled", "");

        assertThat(client.generatePatch(request())).isEmpty();
    }

    @Test
    void generatePatchReturnsFixtureResponseWhenFixtureModeEnabled() {
        ConfiguredCoderModelClient client = new ConfiguredCoderModelClient("fixture", "diff --git a/A.java b/A.java\n");

        assertThat(client.generatePatch(request()))
                .hasValueSatisfying(response -> {
                    assertThat(response.provider()).isEqualTo("LOCAL_FIXTURE");
                    assertThat(response.model()).isEqualTo("fixture-coder");
                    assertThat(response.rawOutput()).startsWith("diff --git");
                });
    }

    @Test
    void generatePatchRejectsEmptyFixtureResponse() {
        ConfiguredCoderModelClient client = new ConfiguredCoderModelClient("fixture", "");

        assertThatThrownBy(() -> client.generatePatch(request()))
                .isInstanceOf(ApiException.class)
                .extracting(exception -> ((ApiException) exception).getCode())
                .isEqualTo("CODER_MODEL_FIXTURE_EMPTY");
    }

    @Test
    void generatePatchRejectsUnsupportedMode() {
        ConfiguredCoderModelClient client = new ConfiguredCoderModelClient("anthropic", "");

        assertThatThrownBy(() -> client.generatePatch(request()))
                .isInstanceOf(ApiException.class)
                .extracting(exception -> ((ApiException) exception).getCode())
                .isEqualTo("CODER_MODEL_MODE_UNSUPPORTED");
    }

    @Test
    void generatePatchCallsOpenAiCompatibleChatCompletionsEndpoint() throws IOException {
        AtomicReference<String> authorization = new AtomicReference<>();
        AtomicReference<String> requestBody = new AtomicReference<>();
        startServer(200, """
                {
                  "model": "gpt-test",
                  "choices": [
                    {
                      "message": {
                        "content": "diff --git a/README.md b/README.md\\n--- a/README.md\\n+++ b/README.md\\n@@ -1 +1,2 @@\\n+Generated by test model\\n"
                      }
                    }
                  ]
                }
                """, authorization, requestBody);
        ConfiguredCoderModelClient client = openAiClient("openai-compatible", serverBaseUrl(), "test-key", "gpt-test");

        CoderModelClient.CoderModelResponse response = client.generatePatch(request()).orElseThrow();

        assertThat(response.provider()).isEqualTo("OPENAI_COMPATIBLE");
        assertThat(response.model()).isEqualTo("gpt-test");
        assertThat(response.rawOutput()).startsWith("diff --git a/README.md b/README.md");
        assertThat(authorization.get()).isEqualTo("Bearer test-key");
        JsonNode body = objectMapper.readTree(requestBody.get());
        assertThat(body.path("model").asText()).isEqualTo("gpt-test");
        assertThat(body.path("max_completion_tokens").asInt()).isEqualTo(2048);
        assertThat(body.path("messages").get(0).path("role").asText()).isEqualTo("developer");
        assertThat(body.path("messages").get(0).path("content").asText())
                .contains("Return only one raw unified diff")
                .contains("diff --git");
        assertThat(body.path("messages").get(1).path("content").asText())
                .contains("Task id: 1")
                .contains("Output a single unified diff only");
    }

    @Test
    void generatePatchRejectsMissingOpenAiApiKey() {
        ConfiguredCoderModelClient client = openAiClient("openai-compatible", "http://127.0.0.1:1/v1", "", "gpt-test");

        assertThatThrownBy(() -> client.generatePatch(request()))
                .isInstanceOf(ApiException.class)
                .extracting(exception -> ((ApiException) exception).getCode())
                .isEqualTo("CODER_MODEL_API_KEY_NOT_CONFIGURED");
    }

    @Test
    void generatePatchRejectsMissingOpenAiModel() {
        ConfiguredCoderModelClient client = openAiClient("openai-compatible", "http://127.0.0.1:1/v1", "test-key", "");

        assertThatThrownBy(() -> client.generatePatch(request()))
                .isInstanceOf(ApiException.class)
                .extracting(exception -> ((ApiException) exception).getCode())
                .isEqualTo("CODER_MODEL_MODEL_NOT_CONFIGURED");
    }

    @Test
    void generatePatchRejectsOpenAiHttpFailure() throws IOException {
        startServer(429, "{\"error\":{\"message\":\"rate limited\"}}", new AtomicReference<>(), new AtomicReference<>());
        ConfiguredCoderModelClient client = openAiClient("openai", serverBaseUrl(), "test-key", "gpt-test");

        assertThatThrownBy(() -> client.generatePatch(request()))
                .isInstanceOf(ApiException.class)
                .extracting(exception -> ((ApiException) exception).getCode())
                .isEqualTo("CODER_MODEL_REQUEST_FAILED");
    }

    private CoderModelClient.CoderModelRequest request() {
        return new CoderModelClient.CoderModelRequest(
                1L,
                "Title",
                "Description",
                "FEATURE",
                "demo",
                "main",
                List.of(new CoderModelClient.CoderContextCandidate(
                        10L,
                        "src/main/java/com/example/demo/UserController.java",
                        "CLASS",
                        "CONTROLLER",
                        "com.example.demo.UserController",
                        12,
                        44,
                        "Handles User endpoints",
                        "class UserController {}"
                ))
        );
    }

    private ConfiguredCoderModelClient openAiClient(String mode, String apiBaseUrl, String apiKey, String model) {
        return new ConfiguredCoderModelClient(
                objectMapper,
                mode,
                "",
                apiBaseUrl,
                apiKey,
                model,
                30,
                2048,
                "developer",
                "",
                "",
                HttpClient.newHttpClient()
        );
    }

    private void startServer(
            int statusCode,
            String responseBody,
            AtomicReference<String> authorization,
            AtomicReference<String> requestBody
    ) throws IOException {
        server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
        server.createContext("/v1/chat/completions", exchange -> {
            authorization.set(exchange.getRequestHeaders().getFirst("Authorization"));
            requestBody.set(new String(exchange.getRequestBody().readAllBytes()));
            byte[] bytes = responseBody.getBytes();
            exchange.getResponseHeaders().set("Content-Type", "application/json");
            exchange.sendResponseHeaders(statusCode, bytes.length);
            try (OutputStream output = exchange.getResponseBody()) {
                output.write(bytes);
            }
        });
        server.start();
    }

    private String serverBaseUrl() {
        return "http://127.0.0.1:" + server.getAddress().getPort() + "/v1";
    }
}
