package com.repopilot.agent.domain;

public enum AgentTaskStatus {
    CREATED,
    REPO_INDEXING,
    PLANNING,
    RETRIEVING_CONTEXT,
    GENERATING_PATCH,
    APPLYING_PATCH_IN_SANDBOX,
    RUNNING_TESTS,
    REPAIRING,
    REVIEWING_PATCH,
    WAITING_HUMAN_APPROVAL,
    CREATING_PULL_REQUEST,
    DONE,
    FAILED_REPO_CLONE,
    FAILED_INDEXING,
    FAILED_CONTEXT_RETRIEVAL,
    FAILED_PATCH_GENERATION,
    FAILED_TEST,
    FAILED_PR_CREATION,
    CANCELLED
}

